resources:
  - name: step001
    type: Gitnp/gittest1
    syntaxVersion: lat
    configuration:      
      test: foo
      bdood: "present"
      
      
pipelines:
  - name: pipelines
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          inputResources:          
            - name: step001           
        execution:
          onExecute:
            - echo "executing step..."
            - printenv 
