
resources:
  - name: git_vijay12
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/runtime
      branches:
        include: master      
        
#   - name: git_vijaykp
#     type: GitRepo
#     configuration:
#       gitProvider: vijay
#       path: vijayreddy1991/runtime
#       branches:
#         include: master        
#       files:  # optional
#         include: ^pipe.yml$  

pipelines:
  - name: pipelines
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          timeoutSeconds: 10         
          inputResources:
            - name: git_vijay12
#             - name: git_vijaykp
        execution:
          onExecute:
            - echo "executing step..."
            - printenv
            
            
            
