resources:
  - name: test1234
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/runtime
#       branches:
#         include: master      
#     version:
#       sha: master
      
pipelines:
  - name: VERSIONLIST
    steps:
      - name: test1
        type: Bash
        configuration:
          affinityGroup: A        
          chronological: true       
#           nodePool: ubuntu16
          runtime:            
            type: host
#             image:
#               custom:
#                 name: drydock/u18go
#                 tag: master          
          inputResources:
               - name: test1234        
        execution:
          onExecute:
            - echo "test"  
            - jfrog --version
            - aws --version
            - git --version
            - eb --version
            - kubectl version --client
            - gcloud --version
            - source /root/.gvm/scripts/gvm
            - gvm list
      
      - name: test2
        type: Bash  
        configuration:
          affinityGroup: A                   
          chronological: true        
#           nodePool: ubuntu16
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18go
                tag: master         
          inputSteps:
              - name: test1
        execution:
          onExecute:
            - echo "test2"  
            - jfrog --version
            - aws --version
            - git --version
            - eb --version
            - kubectl version --client
            - gcloud --version
            - source /root/.gvm/scripts/gvm
            - gvm list

      - name: test3
        type: Bash  
        configuration:
          affinityGroup: A                   
          chronological: true      
#           nodePool: ubuntu16
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18go
                tag: master         
          inputSteps:
              - name: test2
        execution:
          onExecute:
            - echo "test2"  
            - jfrog --version
            - aws --version
            - git --version
            - eb --version
            - kubectl version --client
            - gcloud --version
            - source /root/.gvm/scripts/gvm
            - gvm list

#       - name: test4
#         type: Bash  
#         configuration:
#           affinityGroup: B                 
#           chronological: true        
# #           nodePool: ubuntu16
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: drydock/u18cpp
#                 tag: master         
#           inputSteps:
#               - name: test3
#         execution:
#           onExecute:
#             - echo "test2"  
#             - jfrog --version
#             - aws --version
#             - git --version
#             - eb --version
#             - kubectl version --client
#             - gcloud --version

            
#       - name: test5
#         type: Bash  
#         configuration:   
#           affinityGroup: B            
#           chronological: false    
# #           nodePool: ubuntu16
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: drydock/u18java
#                 tag: master         
#           inputSteps:
#               - name: test4
#         execution:
#           onExecute:
#             - echo "test2"  
#             - jfrog --version
#             - aws --version
#             - git --version
#             - eb --version
#             - kubectl version --client
#             - gcloud --version

#       - name: test6
#         type: Bash  
#         configuration:
#           affinityGroup: B                  
#           chronological: true    
# #           nodePool: ubuntu16
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: drydock/u18java
#                 tag: master         
#           inputSteps:
#               - name: test5
#         execution:
#           onExecute:
#             - echo "test2"  
#             - jfrog --version
#             - aws --version
#             - git --version
#             - eb --version
#             - kubectl version --client
#             - gcloud --version











































































#   - name: webhookIncoming
#     type: Webhook
#     configuration:
#       integrationName: vijay_internal
#     version:
#       payload: "reddy"

#   - name: webhookOutging
#     type: webhook
#     configuration:
#       integrationName: vijay_external
#     version:
#       payload: "vijay"      
      
#   - name: runtimeincoming
#     setup: 
#       environmentVariables:
#         readOnly:
#           Number: 27
#       runtime:       
#         type: image
#         image:
# #           auto:
# #             language: nodejs
# #             versions:
# #               - 10.15.3
#           custom:
#             name: "drydock/u18node"
#             tag: "master"
#             options: "--env VIJAY=kumar"
#         requires:
#           resources:
#              - vijay_internal  
#     steps:    
#       - name: incoming
#         type: bash
# #         setup:
# #           runtime:
# #             type: image
# #             image:
# #              custom:
# #                name: drydock/u18node
# #                tag: master
        #triggeredBy:
        #   resources:
        #     - test
# #         outputResources:
# #           - vijay_external
#         execution:
#           onExecute:
#             - echo "vijay"
# #             - sudo dd if=/dev/urandom of=file.txt count=1000000 bs=1100
#             - printenv
#             - node --version
           
