resources:
  - name: test1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/runtime

pipelines:
  - name: pipelines
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          inputResources:
            - name: test1234
        execution:
          onExecute:
            - echo "executing step..."
            - prin
