
resources:
  - name: test1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:
        include: master      
        
  - name: test12345
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:
        include: master        
      files:  # optional
        include: file1      

pipelines:
  - name: pipelines
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          inputResources:
            - name: test1234
            - name: test12345
        execution:
          onExecute:
            - echo "executing step..."
            
            
            
