
resources:
  - name: git_vijay
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:
        include: master      
        
  - name: git_vijaykp
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:
        include: master        
      files:  # optional
        include: ^pipe.yml$  

pipelines:
  - name: pipelines
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          inputResources:
            - name: git_vijay
            - name: git_vijaykp
        execution:
          onExecute:
            - echo "executing step..."
            
            
            
