resources:
  - name: test1234
    type: GitRepo
    configuration:
      gitProvider: bit
      path: vijayreddy1991/runtime

pipelines:
  - name: pipelines
    steps:
      - name: S_Bash1
        type: Bash
        configuration:
#          affinityGroup: A            
          nodePool: c7test       
          inputResources:
            - name: test1234
        execution:
          onExecute:
            - echo "executing step..."
            - sudo docker images
            - sudo docker ps -a

      - name: S_Bash2
        type: Bash
        configuration:
#          affinityGroup: A            
          nodePool: c7test       
          inputSteps:
            - name: S_Bash1
        execution:
          onExecute:
            - echo "executing step..."
            
      - name: S_Bash3
        type: Bash
        configuration:
#          affinityGroup: A            
          nodePool: c7test        
          inputResources:
            - name: test1234
        execution:
          onExecute:
            - echo "executing step..."
            
#       - name: S_Bash4
#         type: Bash
#         configuration:
# #          affinityGroup: A            
#           nodePool: vijay        
#           inputSteps:
#             - name: S_Bash3
#         execution:
#           onExecute:
#             - echo "executing step..."  
