resources:
      
  - name: vijayRepo
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/powershell

pipelines:
  - name: pipeline_automation
    steps:
      - name: api_pipeline
        type: PowerShell
        configuration:
          nodePool: windows-static
          inputResources:
            - name: vijayRepo            
        execution:
          onExecute:
            - write-output "hi"
            - Get-Variable | format-table
            - write-output "$vijayRepo"
            - Push-Location $res_vijayRepo_resourcePath
            - $buildDir = find_resource_variable vijayRepo $res_vijayRepo_resourcePath
