resources:
      
  - name: myRepo
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/powershell

pipelines:
  - name: pipeline_automation
    steps:
      - name: api_pipeline
        type: PowerShell
        execution:
          onExecute:
            - write-output "hi"
            - buildDir=$(find_resource_variable $inputGitRepoResourceName resourcePath)
