resources:
  - name: test
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/runtime
      branches:
        include: master      
    version:
      sha: master
      
pipelines:
  - name: VERSIONLIST
    steps:
      - name: test1
        type: Bash
        configuration:
          nodePool: ubuntu16
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18node
                tag: master          
        triggeredBy:
           resources:
             - test        
        execution:
          onExecute:
            - echo vijay
            - jfrog --version
            - aws --version
            - git --version
            - eb --version
            - kubectl version --client
            - gcloud --version  
            - node --version
            - nvm --version
            - nvm list
      
      - name: test2
        type: Bash  
        configuration:
          nodePool: ubuntu16
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18go
                tag: master         
        triggeredBy:
          steps:
            - test1
        execution:
          onExecute:
            - echo "test2"  
            - jfrog --version
            - aws --version
            - git --version
            - eb --version
            - kubectl version --client
            - gcloud --version
            - gvm list

      - name: test3
        type: Bash  
        configuration:
          nodePool: ubuntu16
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18cpp
                tag: master          
        triggeredBy:
          steps:
            - test2
        execution:
          onExecute:
            - echo "Test3"
            - jfrog --version
            - aws --version
            - git --version
            - eb --version
            - kubectl version --client
            - gcloud --version
            - clang --version
            - gcc --version

      - name: test4
        type: Bash 
        configuration:
          nodePool: ubuntu16
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master          
        triggeredBy:
          steps:
            - test3
        execution:
          onExecute:
            - echo "test4"
            - jfrog --version
            - aws --version
            - git --version
            - eb --version
            - kubectl version --client
            - gcloud --version
            - gradle --version
            - update-alternatives --config java
            













































































#   - name: webhookIncoming
#     type: Webhook
#     configuration:
#       integrationName: vijay_internal
#     version:
#       payload: "reddy"

#   - name: webhookOutging
#     type: webhook
#     configuration:
#       integrationName: vijay_external
#     version:
#       payload: "vijay"      
      
#   - name: runtimeincoming
#     setup: 
#       environmentVariables:
#         readOnly:
#           Number: 27
#       runtime:       
#         type: image
#         image:
# #           auto:
# #             language: nodejs
# #             versions:
# #               - 10.15.3
#           custom:
#             name: "drydock/u18node"
#             tag: "master"
#             options: "--env VIJAY=kumar"
#         requires:
#           resources:
#              - vijay_internal  
#     steps:    
#       - name: incoming
#         type: bash
# #         setup:
# #           runtime:
# #             type: image
# #             image:
# #              custom:
# #                name: drydock/u18node
# #                tag: master
        #triggeredBy:
        #   resources:
        #     - test
# #         outputResources:
# #           - vijay_external
#         execution:
#           onExecute:
#             - echo "vijay"
# #             - sudo dd if=/dev/urandom of=file.txt count=1000000 bs=1100
#             - printenv
#             - node --version
           
