resources:
  - name: test
    type: gitRepo
    repoPath: vijayreddy1991/sample_pip
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master
  
pipelines:
  - name: runtime
    setup: 
      environmentVariables:
        readOnly:
          Number: 27   
      runtime:       
        type: image
        image:
          auto:
            language: nodejs
            versions: 10.15.3
#           custom:
#             name:
#             tag:
#             options:
    steps:    
      - name: test1
        type: bash
        setup: 
          environmentVariables:
            normal:
              Number: 27 
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16node
#                tag: master
#         triggeredBy:
#           resources:
#             - test
        execution:
          onExecute:
            - echo "hi"
            - node --version

      - name: test2
        type: bash   
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: 
#                tag: master
        triggeredBy:
          steps:
            - test1
        execution:
          onExecute:
            - echo "test2"
            - node --version

      - name: test3
        type: bash  
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16node
#                tag: master
        triggeredBy:
          steps:
            - test2
        execution:
          onExecute:
            - echo "Test3"
            - node --version

      - name: test4
        type: bash   
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16node
#                tag: master
        triggeredBy:
          steps:
            - test3
        execution:
          onExecute:
            - echo "test4"
            - node --version
