resources:
  - name: test
    type: gitRepo
    repoPath: vijayreddy1991/runtime
    configuration:
      integrationName: vijay_git
      branches:
        only: master
    initialVersion:
      sha: master
  - name: webhookIntegrationResource1
    type: webhook
    configuration:
      integrationName: externalWebhook
    initialVersion:
      payload: vijay      
  - name: webhookIntegrationResource2
    type: webhook
    configuration:
      integrationName: incomingWebhookIntegration
    initialVersion:
      payload: "" 

pipelines:
  - name: runtime2
    steps:
      - name: test2
        type: bash
        triggeredBy:
          resources:
            - webhookIntegrationResource2
        execution:
          onExecute:
            - echo yay
  - name: runtime
    setup: 
      environmentVariables:
        readOnly:
          Number: 27   
      runtime:       
        type: image
        image:
#           auto:
#             language: nodejs
#             versions:
#               - 10.15.3
          custom:
            name: "drydock/u18node"
            tag: "master"
            options: "--env VIJAY=kumar"
    steps:    
      - name: test1
        type: bash
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u18node
#                tag: master
        #triggeredBy:
        #   resources:
        #     - test
        outputResource:
          - webhookIntegrationResource1
        execution:
          onExecute:
            - echo "vijay"
#             - sudo dd if=/dev/urandom of=file.txt count=1000000 bs=1100
            - printenv
            - node --version
#             - save_run_state $(pwd)/file.txt impfile

#       - name: test2
#         type: bash   
#         triggeredBy:
#           steps:
#             - test1
#         execution:
#           onExecute:
#             - echo "test2"
            

#       - name: test3
#         type: bash  
#         triggeredBy:
#           steps:
#             - test2
#         execution:
#           onExecute:
#             - echo "Test3"
#             - restore_run_state impfile exmple.txt
#             - du -h

#       - name: test4
#         type: bash 
#         triggeredBy:
#           steps:
#             - test3
#         execution:
#           onExecute:
#             - echo "test4"
#             - restore_run_state impfile exmple.txt
#             - du -h
