resources:
  - name: test
    type: gitRepo
    repoPath: vijayreddy1991/sample_pip
    configuration:
      integrationName: vijay_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: runtime
    setup: 
      environmentVariables:
        readOnly:
          Number: 27   
      runtime:       
        type: 
        image:
          auto:
            language: nodejs
            versions:
              - 10.15.3
#           custom:
#             name: "drydock/u16node"
#             tag: "master"
#             options: "--env VIJAY=kumar"
    steps:    
      - name: test1
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16node
               tag: master
        triggeredBy:
           resources:
             - test
        execution:
          onExecute:
            - echo "hi"
            - printenv
            - add_run_variable FOO_STATE=BAR_VAL

      - name: test2
        type: bash   
        triggeredBy:
          steps:
            - test1
        execution:
          onExecute:
            - echo "test2"
            - add_run_variable FOO_STATE=vijay

      - name: test3
        type: bash  
        triggeredBy:
          steps:
            - test2
        execution:
          onExecute:
            - echo "Test3"
            - echo $FOO_STATE

      - name: test4
        type: bash 
        triggeredBy:
          steps:
            - test3
        execution:
          onExecute:
            - echo "test4"
            - echo $FOO_STATE
