
pipelines:
  - name: pipelines_vijay
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          timeoutSeconds: 7200
          nodePool: nodetest         
          inputResources:          
            - name: test_1234           

        execution:
          onExecute:
            - echo "executing step..."
            - printenv  
